# Types of commands which can be executed.

commands:
  exists:
    -
      exec: command
      args:
        - -v
        - ${cmd}
  install-brew:
    -
      exec: brew
      args:
        - install
        - ${name}
  install-cask:
    -
      exec: brew
      args:
        - cask
        - install
        - ${name}
  install-dart:
    -
      exec: pub
      args:
        - global
        - activate
        - ${name}
  install-npm:
    -
      exec: npm
      args:
        - --global
        - install
        - ${name}
  install-flutter:
    -
      exec: git
      args:
        - clone
        - https://github.com/flutter/flutter.git
        - flutter-sdk
    -
      exec: mv
      args:
        - flutter-sdk/
        - /usr/local/var/flutter-sdk
    -
      exec: rm
      args:
        - -rf
        - flutter-sdk
  nothing:
    -
      exec: echo

# Types of installations available and how to execute them.

types:
  brew:
    install:
      - install-brew
    is_installed:
      - exists
  cask:
    install:
      - install-cask
    is_installed:
      - exists
  dart:
    install:
      - install-dart
    is_installed:
      - exists
  npm:
    install:
      - install-npm
    is_installed:
      - exists
  flutter:
    install:
      - install-flutter
    is_installed:
      - nothing

# The packages to install and which installation type to use.

packages:
  java:
    type: cask
  kotlin:
    type: brew
  ant:
    type: brew
  maven:
    type: brew
    cmd: mvn
  gradle:
    type: brew
  intellij-idea:
    type: cask
    cmd: idea
  aqueduct:
    type: dart
  npm:
    type: brew
  git:
    type: brew
  docker-toolbox:
    type: cask
    cmd: docker
  stagehand:
    type: dart
  yo:
    type: npm
  atom:
    type: cask
  ios-deploy:
    type: brew
  cocoapods:
    type: brew
    cmd: pod
  android-sdk:
    type: cask
    cmd: android
    bash:
      - export ANDROID_HOME=/usr/local/bin/android
      - export PATH=$PATH:\$ANDROID_HOME/tools
      - export PATH=$PATH:\$ANDROID_HOME/tools/bin
      - export PATH=$PATH/:\$ANDROID_HOME/platform-tools
  angular_cli:
    type: dart
    cmd: ngdart
  npm-gui:
    type: npm
  flutter:
    type: flutter
    bash:
      - export PATH=/usr/local/var/flutter-sdk/bin:$PATH

# Collections are logical groups of packages.
# A collection can have many packages and nested collections.
# Hidden collections are useful for composition but they won't show up in the menu.

collections:
  java:
    hidden: true
    packages:
      - java
      - kotlin
      - ant
      - maven
      - gradle
      - intellij-idea
  basic:
    hidden: true
    packages:
      - npm
      - atom
  web:
    packages:
      - angular_cli
      - npm-gui
    collections:
      - basic
  mobile:
    packages:
      - android-sdk
      - ios-deploy
      - cocoapods
      - flutter
    collections:
      - basic
      - java
  backend:
    packages:
      - aqueduct
    collections:
      - basic
      - java
  frontend:
    collections:
      - basic
      - mobile
      - web
  all:
    collections:
      - basic
      - mobile
      - web
