# Types of installations available and how to execute them.

types:
  brew:
    install:
      - brew install {name}
    is_installed:
      - command -v {cmd}
  cask:
    install:
      - brew cask install {name}
    is_installed:
      - command -v {cmd}
  dart:
    install:
      - pub global activate {name}
    is_installed:
      - command -v {cmd}
  npm:
    install:
      - npm install --global {name}
    is_installed:
      - command -v {cmd}

# The packages to install and which installation type to use.

packages:
  java:
    type: cask
  kotlin:
    type: brew
  ant:
    type: brew
  maven:
    type: brew
    cmd: mvn
  gradle:
    type: brew
  intellij-idea:
    type: cask
    cmd: idea
  aqueduct:
    type: dart
  npm:
    type: brew
  git:
    type: brew
  docker-toolbox:
    type: cask
    cmd: docker
  stagehand:
    type: dart
  yo:
    type: npm
  atom:
    type: cask
  ios-deploy:
    type: brew
  cocoapods:
    type: brew
    cmd: pod
  android-sdk:
    type: cask
    cmd: android
    bash:
      - export ANDROID_HOME=/usr/local/bin/android
      - export PATH=\$PATH:\$ANDROID_HOME/tools
      - export PATH=\$PATH:\$ANDROID_HOME/tools/bin
      - export PATH=\$PATH/:\$ANDROID_HOME/platform-tools
  angular_cli:
    type: dart
    cmd: ngdart
  npm-gui:
    type: npm
  spotify:
    type: cask
  google-chrome:
    type: cask

# Collections are logical groups of packages.
# A collection can have many packages and nested collections.
# Hidden collections are useful for composition but they won't show up in the menu.

collections:
  java:
    hidden: true
    packages:
      - java
      - kotlin
      - ant
      - maven
      - gradle
      - intellij-idea
  basic:
    packages:
      - npm
  extras:
    packages:
      - git
      - docker-toolbox
      - stagehand
      - yo
      - atom
      - npm-gui
    collections:
      - basic
  web:
    packages:
      - angular_cli
      - google-chrome
    collections:
      - basic
  mobile:
    packages:
      - android-sdk
      - ios-deploy
      - cocoapods
    collections:
      - basic
      - java
  backend:
    packages:
      - aqueduct
    collections:
      - basic
      - java
  frontend:
    collections:
      - basic
      - mobile
      - web
  dev-all:
    collections:
      - basic
      - mobile
      - web
      - extras
  software:
    packages:
      - spotify
      - google-chrome
      - intellij-idea
      - atom
  media:
    packages:
      - spotify
      - google-chrome
  all:
    collections:
      - dev-all
      - software
